/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VmsRouteImport } from './routes/vms'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVmsRouteImport } from './routes/admin/vms'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminMonitoringRouteImport } from './routes/admin/monitoring'
import { Route as AdminIpPoolsRouteImport } from './routes/admin/ip-pools'
import { Route as AdminCreateVmRouteImport } from './routes/admin/create-vm'
import { Route as AdminClustersRouteImport } from './routes/admin/clusters'

const VmsRoute = VmsRouteImport.update({
  id: '/vms',
  path: '/vms',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVmsRoute = AdminVmsRouteImport.update({
  id: '/admin/vms',
  path: '/admin/vms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIpPoolsRoute = AdminIpPoolsRouteImport.update({
  id: '/admin/ip-pools',
  path: '/admin/ip-pools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateVmRoute = AdminCreateVmRouteImport.update({
  id: '/admin/create-vm',
  path: '/admin/create-vm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersRoute = AdminClustersRouteImport.update({
  id: '/admin/clusters',
  path: '/admin/clusters',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/vms': typeof VmsRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/create-vm': typeof AdminCreateVmRoute
  '/admin/ip-pools': typeof AdminIpPoolsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vms': typeof AdminVmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/vms': typeof VmsRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/create-vm': typeof AdminCreateVmRoute
  '/admin/ip-pools': typeof AdminIpPoolsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vms': typeof AdminVmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/vms': typeof VmsRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/create-vm': typeof AdminCreateVmRoute
  '/admin/ip-pools': typeof AdminIpPoolsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vms': typeof AdminVmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/vms'
    | '/admin/clusters'
    | '/admin/create-vm'
    | '/admin/ip-pools'
    | '/admin/monitoring'
    | '/admin/users'
    | '/admin/vms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/vms'
    | '/admin/clusters'
    | '/admin/create-vm'
    | '/admin/ip-pools'
    | '/admin/monitoring'
    | '/admin/users'
    | '/admin/vms'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/vms'
    | '/admin/clusters'
    | '/admin/create-vm'
    | '/admin/ip-pools'
    | '/admin/monitoring'
    | '/admin/users'
    | '/admin/vms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRoute
  VmsRoute: typeof VmsRoute
  AdminClustersRoute: typeof AdminClustersRoute
  AdminCreateVmRoute: typeof AdminCreateVmRoute
  AdminIpPoolsRoute: typeof AdminIpPoolsRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVmsRoute: typeof AdminVmsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vms': {
      id: '/vms'
      path: '/vms'
      fullPath: '/vms'
      preLoaderRoute: typeof VmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vms': {
      id: '/admin/vms'
      path: '/admin/vms'
      fullPath: '/admin/vms'
      preLoaderRoute: typeof AdminVmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ip-pools': {
      id: '/admin/ip-pools'
      path: '/admin/ip-pools'
      fullPath: '/admin/ip-pools'
      preLoaderRoute: typeof AdminIpPoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-vm': {
      id: '/admin/create-vm'
      path: '/admin/create-vm'
      fullPath: '/admin/create-vm'
      preLoaderRoute: typeof AdminCreateVmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clusters': {
      id: '/admin/clusters'
      path: '/admin/clusters'
      fullPath: '/admin/clusters'
      preLoaderRoute: typeof AdminClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRoute,
  VmsRoute: VmsRoute,
  AdminClustersRoute: AdminClustersRoute,
  AdminCreateVmRoute: AdminCreateVmRoute,
  AdminIpPoolsRoute: AdminIpPoolsRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVmsRoute: AdminVmsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
